## To run docker PostGres db instance, please follow below commands

## To start the docker container
# docker-compose up -d

## To stop the docker container
# docker-compose down


version: '3.9'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=passw@rd
      - POSTGRES_USER=db_user
      - POSTGRES_DB=app-db

