version: '3.9'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=passw@rd
      - POSTGRES_USER=db_user
      - POSTGRES_DB=app-db